function setup_path()
{
   if command -v asdf &>/dev/null; then
      export ASDF_DATA_DIR="$HOME/.local/share/asdf-vm"
      PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
   fi

   LOCAL="$HOME/.local/bin"
   BUN="/home/majunior/.cache/.bun/bin"
   GO="/home/majunior/.local/share/asdf-vm/installs/golang/1.26.3/bin"

   PATH="$LOCAL:$BUN:$GO:$PATH"
   export PATH
}

# change the current working directory when exiting Yazi
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd <"$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}


function filesize()
{
    du -sh * | sort -h
}


function pkgsize() {
    if [ -z "$1" ]; then
        echo "Error: Provide package name (e.g., pkgsize clang)"
        return 1
    fi
    nix path-info -sh --closure-size "nixpkgs#$1"
}


# Starts a tmux session named after a pokemon
function pokemux()
{
    export tmuxmon=$(pokemon-colorscripts -r | head -1)
    tmux new -s "$tmuxmon"
}


# Starts fastfetch with a pokemon with the same name as the zellij session
function pokefetch()
{
    # check if fastfetch is installed
    if ! command -v fastfetch &>/dev/null; then
        return
    fi

    # check if tmux is installed
    if tmux ls >/dev/null 2>&1; then
        # Get the tmux session name and update the exported variable.
        # The variable must be set again like this in case we change the tmux
        # session to another pokemon name.
        export tmuxmon=$(tmux display-message -p '#S')

        if [ -n "$tmuxmon" ]; then
            pokemon-colorscripts \
                --no-title -n "$tmuxmon" |
                fastfetch \
                --logo-type file-raw \
                --logo-height 10 \
                --logo-width 5 \
                --logo -
            return
        fi
    fi
    # If tmux is not installed or we're not in a session, show a random pokemon
    pokemon-colorscripts --no-title -r |
        fastfetch \
            --logo-type file-raw \
            --logo-height 10 \
            --logo-width 5 \
            --logo -
}

# Starts fastfetch with a pokemon with the same name as the zellij session
function pokefetchz()
{
    # check if fastfetch is installed
    if ! command -v fastfetch &>/dev/null; then
        return
    fi

    # check if zellij is installed
    if command -v zellij &>/dev/null; then
        # Get the zellij session name and update the exported variable.
        # The variable must be set again like this in case we change the zellij
        # session to another pokemon name.
        export ZELLIJ_POKEMON_NAME=$(zellij list-sessions | \grep '(current)' | sed -r "s/\x1b\[[0-9;]*m//g" | awk '{print $1}')

        # Check if the variable is set (i.e., we're inside a zellij session)
        if [ -n "$ZELLIJ_POKEMON_NAME" ]; then
            pokemon-colorscripts \
                --no-title -n "$ZELLIJ_POKEMON_NAME" |
                fastfetch \
                    --logo-type file-raw \
                    --logo-height 10 \
                    --logo-width 5 \
                    --logo -
            return
        fi
    fi

    # If zellij is not installed or we're not in a session, show a random pokemon
    pokemon-colorscripts --no-title -r |
        fastfetch \
            --logo-type file-raw \
            --logo-height 10 \
            --logo-width 5 \
            --logo -
}


# Starts a zellij session with a random pokemon name
function pokezellij() {
    # Pick a random Pokémon name from the list provided by pokemon-colorscripts.
    POKEMON_NAME=$(pokemon-colorscripts -l | shuf -n 1)
    # Export the name as an environment variable.
    export ZELLIJ_POKEMON_NAME="$POKEMON_NAME"
    # start Zellij with the session named after the Pokémon.
    zellij --session "$POKEMON_NAME"
}

# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
webm2mp4() {
    input_file="$1"
    output_file="${input_file%.webm}.mp4"
    ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
}

png2webp() {
    ffmpeg -i "$@"
}
