$primary = rgb(6795e4)
$surface = rgb(121b2c)
$secondary = rgb(dc7388)
$error = rgb(d07f8f)
$tertiary = rgb(a766cc)
$surface_lowest = rgb(090e16)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
