[timer]
# Enabling this will only consider user input alone for idle state, e.g. you will not have breaks when watching videos or playing music without any user input.
ignore_idle_inhibitors = false
# Timer will stop and reset when you are idle for this amount of seconds.
idle_timeout = 130 # 2 min + 10 sec
# Active duration that activates a break.
short_break_timeout = 1200 # 20 min
long_break_timeout = 7200 # 120 min
# Breaks duration.
short_break_duration = 120 # 2 min
long_break_duration = 1200 # 20 min

[notification]
show_progress_bar = true
# Minimum delay of updating the progress bar (lower than 1s may return an error).
minimum_update_delay = 2
