[main]
include=~/.config/foot/themes/noctalia

# Do `fc-list : family` to get installed fonts
#font=FantasqueSansM Nerd Font Propo:size=12.5
#font=Iosevka Nerd Font Propo:size=15.0
font=IosevkaTerm Slab Nerd Font Propo:size=15.0

[tweak]
font-monospace-warn=no
