[main]
include=~/.config/foot/themes/noctalia

term=xterm-256color

# Do `fc-list : family` to get installed fonts
#font=FantasqueSansM Nerd Font Propo:size=12.5
#font=Iosevka Nerd Font Propo:size=12.0
font=IosevkaTerm Slab Nerd Font Propo:size=11.5

[tweak]
font-monospace-warn=no
