# Keep mouse enabled but disable scroll
set -g mouse on
unbind -n WheelUpPane
unbind -n WheelDownPane

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# New tmux session (Ctrl+n)
bind-key -r n run-shell "tmux new"

# Last/previous session (Alt+p)
bind -n M-p switch-client -l

# Tmux-sessionizer on projects (Ctrl+f)
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

### Status bar
# Status bar position (top or bottom)
set -g status-position bottom

# Status bar colors
set -g status-bg colour235
set -g status-fg colour250

# Left side of status bar
set -g status-left-length 40
set -g status-left "#[fg=green][#S] #[fg=yellow]Tab:#I #[fg=cyan]Pane:#P"

# Right side of status bar
set -g status-right-length 80
set -g status-right ""
# set -g status-right "#[fg=cyan]%H:%M #[fg=yellow]%d-%b-%y"

# Window status format
setw -g window-status-current-format ""
# setw -g window-status-format "#[fg=colour244] #I:#W "
# setw -g window-status-current-format "#[fg=colour16,bg=colour39,bold]Pane: #I/#W "

# Center window list
set -g status-justify centre
