[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "smolbar", "fullbar" ]

    [bar.fullbar]
    background_opacity = 0.74999998323619366
    end = [ "notifications", "tray", "bar_2", "group:g2", "network", "group:g1", "session" ]
    margin_ends = 0
    radius = 0
    start = [ "launcher", "taskbar" ]
    thickness = 26
    widget_spacing = 16

        [bar.fullbar.dead_zone.actions]
        scroll_down = "exec niri msg action focus-column-right"
        scroll_up = "exec niri msg action focus-column-left"

        [[bar.fullbar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "power_profile", "battery" ]
        opacity = 1.0
        padding = 0.0
        widget_spacing = 6

        [[bar.fullbar.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "volume", "input_volume" ]
        opacity = 1.0
        padding = 6.0

    [bar.smolbar]
    background_opacity = 0.69999998435378075
    border_width = 1.0
    center = [ "notifications", "clock", "bar", "task" ]
    concave_edge_corners = false
    contact_shadow = true
    enabled = false
    end = [ "tray", "network", "bluetooth", "group:g1", "power_profile", "battery", "session" ]
    font_weight = 400
    margin_ends = 300
    radius = 6
    start = [ "launcher", "cat", "taskbar" ]
    widget_spacing = 14

        [bar.smolbar.dead_zone.actions]
        scroll_down = "exec niri msg action focus-column-right"
        scroll_up = "exec niri msg action focus-column-left"

        [bar.smolbar.monitor.HDMI-A-2]
        margin_ends = 550

        [[bar.smolbar.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "volume", "input_volume" ]
        opacity = 1.0
        padding = 6.0

[battery]
warning_threshold = 15

    [battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
    warning_threshold = 15

[config]

[control_center]
sidebar = "full"
sidebar_section = "full"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "clipboard"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "caffeine"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[hot_corners]
enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 3

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 150.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1200.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 120.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
address = "Curitiba, Brasil"

[lockscreen]
blur_intensity = 0.0
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000008"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 70.0
    box_width = 256.0
    cx = 960.0
    cy = 895.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 32.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 32.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 256.0
    cx = 1104.0
    cy = 718.1251220703125
    output = "eDP-1"
    placement_height = 810.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 8.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 8.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 820.00006103515625
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 176.0
    box_width = 176.0
    cx = 1102.500244140625
    cy = 637.5001220703125
    output = "eDP-1"
    placement_height = 810.0
    placement_width = 1440.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        background_padding = 0
        background_radius = 32
        center_text = true
        clock_style = "digital"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 48.0
    box_width = 48.0
    cx = 952.0
    cy = 718.1251220703125
    output = "eDP-1"
    placement_height = 810.0
    placement_width = 1440.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        command = "systemctl suspend"
        glyph = "moon-filled"
        label = ""
        variant = "default"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 48.0
    box_width = 48.0
    cx = 1256.0
    cy = 718.1251220703125
    output = "eDP-1"
    placement_height = 810.0
    placement_width = 1440.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = true
        color = "on_error"
        command = "poweroff"
        glyph = "power"
        label = ""
        variant = "destructive"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 192.0
    box_width = 272.0
    cx = 1144.0
    cy = 213.0
    output = "eDP-1"
    placement_height = 810.0
    placement_width = 1440.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        background_padding = 0
        background_radius = 8
        forecast_days = 2
        shadow = false
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 928.0
    cy = 952.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = true
        color = "on_secondary"
        command = "systemctl suspend"
        glyph = "moon-filled"
        variant = "secondary"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 996.0
    cy = 952.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background = true
        color = "on_error"
        command = "poweroff"
        glyph = "power"
        variant = "destructive"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 80.0
    box_width = 160.0
    cx = 960.0
    cy = 164.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

[nightlight]
enabled = true

[notification]
filter_order = [ "filter" ]
layer = "overlay"

    [notification.filter.filter]
    allow_permanent = true
    bypass_dnd = false
    enabled = true
    match = "app.zen_browser.zen"
    play_sound = false
    save_history = true
    show_toast = true

[plugin_settings."alexander/screen-toolkit"]
selected-ocr-lang = "eng+ptbr"

[plugin_settings."blackbartblues/audio-switcher"]
show_notification_on_switch = false
show_percentage = false

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true

[plugin_settings."oldirtty/color_picker"]
panel_position = "auto"

[plugins]
enabled = [ "dotnetrob/cat", "noctalia/timer", "noctalia/wallhaven" ]

[shell]
avatar_path = "/home/majunior/Documents/harvestmoonavatar.png"
font_family = "FantasqueSansM Nerd Font Propo"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = true

    [shell.launcher]
    pinned = [ "app.zen_browser.zen", "foot", "org.mozilla.thunderbird_esr", "io.github.kolunmi.Bazaar", "yazi" ]

    [shell.panel]
    floating_layer = "top"
    launcher_placement = "attached"
    open_near_click_control_center = true
    open_near_click_launcher = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 8

    [shell.screenshot]
    confirm_region = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "q"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "p"
    variant = "destructive"

[templates]

[theme]
builtin = "Nord"
community_palette = "Nord Aurora"
mode = "dark"
source = "community"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "foot", "gtk3", "gtk4", "niri", "qt", "starship" ]
    community_ids = [ "zen-browser", "yazi" ]

[wallpaper.default]
path = "/home/majunior/Pictures/wallhaven-qdwjvq.png"

[wallpaper.last]
path = "/home/majunior/Pictures/wallhaven-qdwjvq.png"

[wallpaper.monitors.HDMI-A-2]
path = "/home/majunior/Pictures/wallhaven-qdwjvq.png"

[wallpaper.monitors.eDP-1]
path = "/home/majunior/Pictures/wallhaven-qdwjvq.png"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/majunior/Pictures/Wallpapers/wallhaven-rq6yqm.jpg"
theme_mode = "dark"
wallpaper_scheme = "soft"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/majunior/Pictures/Wallpapers/wallhaven-wemx96.png"
theme_mode = "dark"
wallpaper_scheme = "soft"

[widget.bar]
enable_scroll = false
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.battery]
display_mode = "graphic"
scale = 0.75
show_label = false

[widget.brightness]
show_label = false

[widget.cat]
cat_color = "primary"
cat_size = 30
type = "dotnetrob/cat:cat"

    [widget.cat.actions]
    left = "exec foot -e btop"
    right = "exec foot -e yazi"

[widget.clock]
format = "{:%H%M} - {:%d/%m}"

[widget.input_volume]
show_label = false

[widget.launcher]
glyph = "noctalia"

    [widget.launcher.actions]
    right = "exec noctalia msg panel-toggle noctalia/wallhaven:browser"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.task]
text = "   "
type = "text"

[widget.taskbar]
active_indicator_color = "on_surface"
icon_scale = 1.5000000000000002
inactive_opacity = 0.65000000000000002
item_spacing = 8
show_all_outputs = true
show_workspace_label = false

    [widget.taskbar.actions]
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

[widget.volume]
show_label = false

    [widget.volume.actions]
    right = "exec /home/majunior/dotfiles/.config/niri/scripts/audio-mgmt.sh"

[widget.workspaces]
max_label_chars = 3
show_all_outputs = true
style = "focus_hint"
