[backdrop]
enabled = true

[bar.default]
center = [ "notifications", "clock", "bar" ]
concave_edge_corners = false
end = [ "tray", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 4
margin_ends = 400
radius = 8
start = [ "launcher", "control-center", "taskbar" ]
thickness = 30
widget_spacing = 14

    [bar.default.dead_zone.actions]
    scroll_down = "exec niri msg action focus-column-right"
    scroll_up = "exec niri msg action focus-column-left"

[config]

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "wallpaper"

[desktop_widgets]
enabled = false

[hot_corners]
enabled = true

    [hot_corners.top_left]
    action = "window_switcher"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 150.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 1200.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 120.0

[location]
address = "Curitiba, Brasil"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2", "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 682.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 540.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "clock"

[notification]
layer = "overlay"
position = "top_center"

[plugins]
enabled = [ "noctalia/timer", "noctalia/wallhaven", "dotnetrob/cat" ]

[shell]
avatar_path = "/home/majunior/Documents/harvestmoonavatar.png"
niri_overview_type_to_launch_enabled = true
polkit_agent = true
screen_time_enabled = true

    [shell.launcher]
    app_grid = true

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    floating_layer = "top"
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.session]
    grid = true

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "l"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "s"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "q"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "r"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "p"
        variant = "destructive"

[templates]

[theme]
builtin = "Nord"
community_palette = "One Dark Two"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "foot", "gtk3", "gtk4", "niri", "qt", "starship" ]
    community_ids = [ "zen-browser", "yazi" ]

[wallpaper.default]
path = "/home/majunior/Pictures/Wallpapers/wallhaven_yjgerk.jpg"

[wallpaper.last]
path = "/home/majunior/Pictures/Wallpapers/wallhaven_yjgerk.jpg"

[wallpaper.monitors.HDMI-A-2]
path = "/home/majunior/Pictures/Wallpapers/wallhaven_yjgerk.jpg"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.clock]
format = "{:%H%M} - {:%d/%m}"

[widget.launcher]
glyph = "snowflake"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.taskbar]
group_by_workspace = true
inactive_opacity = 0.75
show_all_outputs = true

[widget.volume.actions]
middle = "exec pavucontrol"

[widget.workspaces]
max_label_chars = 3
