
[window]
dimensions.columns = 121
dimensions.lines = 40

[colors]
[colors.primary]
foreground = '#ffffff'
background = '#000000'

[general]
# Used by the Activity.desktop app
import = [ "~/.config/alacritty/pane.toml" ]
