[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/home/majunior/dotfiles/.local/bin/poke-zellij.sh"

[window]
padding.x = 7
padding.y = 5
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
