[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/home/majunior/dotfiles/.local/scripts/poke-zellij.sh"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
