-- transparent background
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "none" })
vim.api.nvim_set_hl(0, "Terminal", { bg = "none" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "Folded", { bg = "none" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
vim.api.nvim_set_hl(0, "WhichKeyFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = "none" })

-- transparent background for neotree
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "none" })
vim.api.nvim_set_hl(0, "NeoTreeVertSplit", { bg = "none" })
vim.api.nvim_set_hl(0, "NeoTreeWinSeparator", { bg = "none" })
vim.api.nvim_set_hl(0, "NeoTreeEndOfBuffer", { bg = "none" })

-- transparent background for nvim-tree
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "NvimTreeVertSplit", { bg = "none" })
vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { bg = "none" })

-- transparent notify background
vim.api.nvim_set_hl(0, "NotifyINFOBody", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyERRORBody", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyWARNBody", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyTRACEBody", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyDEBUGBody", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyINFOTitle", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyERRORTitle", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyWARNTitle", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyTRACETitle", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyINFOBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyERRORBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyWARNBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", { bg = "none" })

-- lualine transparency
vim.api.nvim_set_hl(0, "lualine_a_normal", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_b_normal", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_c_normal", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_x_normal", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_y_normal", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_z_normal", { bg = "none" })
-- for other modes (insert, visual, etc.)
vim.api.nvim_set_hl(0, "lualine_a_insert", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_a_visual", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_a_replace", { bg = "none" })
vim.api.nvim_set_hl(0, "lualine_a_command", { bg = "none" })

-- bufferline transparency
vim.api.nvim_set_hl(0, "BufferLineFill", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineBackground", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineTab", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineTabSelected", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineTabSeparator", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineBuffer", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineBufferSelected", { bg = "none" })
vim.api.nvim_set_hl(0, "BufferLineBufferVisible", { bg = "none" })

-- snacks transparency
vim.api.nvim_set_hl(0, "SnacksDashboardNormal", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksNotifierInfo", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksNotifierWarn", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksNotifierError", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksNotifierDebug", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksNotifierTrace", { bg = "none" })
vim.api.nvim_set_hl(0, "SnacksPickerTree", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { bg = "none" })
